### PR TITLE
Main

### PR DESCRIPTION
**Pull request by habib-Bashi**
new updates like project page and changes made in cv

### CODE REVIEW

**Comment by habib-Bashi** [comment]
new changes marge from main to main

**Comment by piazzai** [comment]
Hi! It seems you are customizing the website. That's great to know. But these changes should not be pulled into the template's repository.

**Comment by habib-Bashi** [comment]
Good afternoon,

I am sorry for that; I did not do it deliberately, and please tell me how
to revert it.

I am just trying to push my new changes from my local environment to my
repository on git hub, but my new changes were not reflected on my website.



With thanks,
Habib Ullah

**Comment by piazzai** [comment]
No problem! I turned down the pull requests and there is no need for further action.

**Pull request closed without merging**
